#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Default editor
export EDITOR="vim"

# Rbenv
if which rbenv > /dev/null;
then
	eval "$(rbenv init -)"
fi

# Java
export JAVA_HOME=$(/usr/libexec/java_home)

# Add path to android tools
export ANDROID_SDK=/Users/m1r4ge/Library/Android/sdk
export PATH=$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$PATH

# iOS
export DEVELOPER_DIR=`xcode-select -p`
alias symbolicatecrash="/Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKitBase.framework/Versions/A/Resources/symbolicatecrash"

